# Generated by Django 3.2.2 on 2021-06-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compny_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(default='', max_length=200)),
                ('custMail', models.EmailField(default='', max_length=200)),
                ('custCon', models.CharField(default='', max_length=200)),
                ('custAdd', models.CharField(default='', max_length=200)),
                ('custRgdate', models.DateTimeField(auto_now=True, null=True)),
                ('custProfile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Customer_Profile/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.compny_details')),
            ],
        ),
    ]
