# Generated by Django 3.2.2 on 2021-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_compny_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='compny_customers',
            name='custPass',
            field=models.CharField(default='', max_length=20),
        ),
    ]
