# Generated by Django 3.2.2 on 2021-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_compny_customers_custpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compny_customers',
            name='custPass',
        ),
    ]
