# Generated by Django 3.2.2 on 2021-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_compny_customers_custpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='compny_customers',
            name='custPass',
            field=models.CharField(default='', max_length=20),
        ),
    ]
