# Generated by Django 3.2.2 on 2021-06-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_compny_customers_custpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compny_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(default='', max_length=200)),
                ('proPrice', models.PositiveBigIntegerField(default=0)),
                ('proQnty', models.PositiveBigIntegerField(default=0)),
                ('proImg', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Product_Photos/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.compny_details')),
            ],
        ),
    ]
