# Generated by Django 3.2.2 on 2021-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_customer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_feedback',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
