# Generated by Django 3.2.2 on 2021-06-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_customer_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_feedback',
            name='comp',
        ),
    ]
