# Generated by Django 3.2.2 on 2021-06-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_customer_feedback_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_feedback',
            name='cust',
        ),
    ]
