# Generated by Django 3.2.2 on 2021-06-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_customer_feedback_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_feedback',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.compny_customers'),
        ),
    ]
