# Generated by Django 3.2.2 on 2021-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_customer_feedback_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_feedback',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
